name: tandem
excludes:
  - node_modules
pluginDirs:
  - plugins
proxy:
  docs:
    - docs-tandem.lndo.site:8010
  site:
    - site-tandem.lndo.site:8011
services:
  docs:
    type: node:12
    ssl: true
    sslExpose: false
    build:
      - yarn install
    command: yarn run dev:docs
    port: 8010
  site:
    type: node:12
    ssl: true
    sslExpose: false
    build:
      - yarn install
    command: yarn run dev:site
    port: 8011
tooling:
  docs:
    service: docs
    cmd: yarn dev:docs
    description: Launch the documentation site
  site:
    service: site
    cmd: yarn dev:site
    description: Launch the marketing site
  node:
    service: docs
  vuepress:
    service: docs
  yarn:
    service: docs
  lint:
    service: docs
    cmd:
      - yarn run lint:docs
      - yarn run lint:site
      - yarn run lint:plugins
    description: Lint the things
