# Core config
name: app
type: nodejs:10
build:
  flavor: none
web:
  commands:
    # Run a no-op process that uses no CPU resources, since this is a static site.
    start: sleep infinity
  locations:
    "/":
      root: "_book"
      index:
        - "index.html"
      expires: 300s
      passthru: false
      scripts: true
      allow: false
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        ^/robots\.txt$:
          allow: true
        search_index\.json$:
          allow: true
        ^/sitemap\.xml$:
          allow: true
disk: 2048
dependencies:
  nodejs:
    yarn: "*"

# Automation
hooks:
  build: |
    set -e
    yarn install
    yarn run build
    curl -sS https://platform.sh/cli/installer | php

# The configuration of scheduled execution.
crons:
  snapshot:
    # Take a snapshot automatically every night at 3 am (UTC).
    spec: '0 3 * * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        /app/.platformsh/bin/platform snapshot:create --yes --no-wait
      fi
  renewcert:
    # Force a redeploy at 9 am (UTC) on the 14th of every month.
    spec: '0 9 14 * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        /app/.platformsh/bin/platform redeploy --yes --no-wait
      fi
