[build]
  base = "./site"
  publish = ".site/.vuepress/dist"
  command = "npm run build"

# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches public assets
[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# pluginz
# https://github.com/netlify/netlify-plugin-lighthouse#readme
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

[[redirects]]
  from   = "http://thinktandem.io/*"
  to     = "https://www.thinktandem.io/:splat"
  status = 301
  force  = true
[[redirects]]
  from   = "https://thinktandem.io/*"
  to     = "https://www.thinktandem.io/:splat"
  status = 301
  force  = true
[[redirects]]
  from   = "http://www.thinktandem.io/*"
  to     = "https://www.thinktandem.io/:splat"
  status = 301
  force  = true
